# Generated by Django 4.2.10 on 2026-02-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
